refactor fix: Fixed runtime error
Fixed the "AttributeError: 'Settings' object has no attribute 'EMAIL_VERIFY_URL'",
by removing the variable entirely. Also re-visted documentation, and included the
missing ones. Changed "FRONTEND_BASE_URL" TO "FRONTEND_ORIGIN".