fix: Fixed Unusual passing of bytes object into celery tasks
Resolved this error: `AttributeError: 'bytes' object has no attribute 'get'`,
which lead to `UnboundLocalError: cannot access local variable 'reference'
where it is not associated with a value`.
In `apps/payments/views.py`: I updated the logic to parse the `request.body`
 into a standard Python dictionary (data = json.loads(payload)) before passing
 it to `.delay()`. Now, Celery cleanly receives a perfectly valid JSON object.
In `tasks/process_webhooks.py`: I improved the code to expect the dictionary
 instead of raw strings/bytes. Additionally, I initialized `reference = None`
 and `tx_ref = None` at the top of the functions so that even if the JSON parsing
 somehow fails, the exception handlers can log the error without crashing.